# Variable Description

The data linked to from the course website represent data collected from the accelerometers from the Samsung Galaxy S smartphone. A full description is available at the site where the data was obtained:

http://archive.ics.uci.edu/ml/datasets/Human+Activity+Recognition+Using+Smartphones

Here are the data for the project:

https://d396qusza40orc.cloudfront.net/getdata%2Fprojectfiles%2FUCI%20HAR%20Dataset.zip

For the purposes of this project, the files in the Inertial Signals folders are not used. The files that will be used to load data are listed as follows:

    test/subject_test.txt
    test/X_test.txt
    test/y_test.txt
    train/subject_train.txt
    train/X_train.txt
    train/y_train.txt

From the dataset, we can see:

    Values of Varible Activity consist of data from “Y_train.txt” and “Y_test.txt”
    values of Varible Subject consist of data from “subject_train.txt” and subject_test.txt"
    Values of Varibles Features consist of data from “X_train.txt” and “X_test.txt”
    Names of Varibles Features come from “features.txt”
    levels of Varible Activity come from “activity_labels.txt”

So we will use Activity, Subject and Features as part of descriptive variable names for data in data frame.

Use descriptive activity names to name the activities in the data set

1.Read descriptive activity names from “activity_labels.txt”
2. facorize Variale activity in the data frame Data using descriptive activity names
3. Check Data Activity

Then appropriately labels the data set with descriptive variable names

In the former part, variables activity and subject and names of the activities have been labelled using descriptive names.In this part, Names of Feteatures will labelled using descriptive variable names.

    prefix t is replaced by time
    Acc is replaced by Accelerometer
    Gyro is replaced by Gyroscope
    prefix f is replaced by frequency
    Mag is replaced by Magnitude
    BodyBody is replaced by Body
    
  Lastly, create a second,independent tidy data set and ouput it

In this part,a second, independent tidy data set will be created with the average of each variable for each activity and each subject based on the data set in step 4.

write.table(Data2, file = "tidydata.txt",row.name=FALSE)

Produce Codebook

library(knitr)
knit2html("codebook.Rmd");

